### ISSUE TITLE
Uncaught ReferenceError: path is not defined

### ISSUE THREAD

**Issue by bronson** [atom/keybinding-resolver#22]
1. bring up pane, hit ctrl-p or something
2. flail on escape and some other keys trying to close it.  I don't remember exactly which keys, I just remember thinking, "now how the heck do I close this pane?"  Yes, I'm a vim-mode user.

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [keybinding-resolver](https://github.com/atom/keybinding-resolver) package, v0.32.0

### Stack Trace

Uncaught ReferenceError: path is not defined

```
At /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/keybinding-resolver/lib/keybinding-resolver-view.js:227

ReferenceError: path is not defined
  at KeyBindingResolverView.module.exports.KeyBindingResolverView.isInAsarArchive (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/keybinding-resolver/lib/keybinding-resolver-view.js:227:57)
  at KeyBindingResolverView.module.exports.KeyBindingResolverView.openKeybindingFile (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/keybinding-resolver/lib/keybinding-resolver-view.js:241:16)
  at HTMLTableCellElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/keybinding-resolver/lib/keybinding-resolver-view.js:44:24)
  at space-pen-div.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
 11x -6:10.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -6:09.7.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -6:09.2.0 ex-mode:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -6:08.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:25.1.0 core:close (div.markdown-preview.native-key-bindings)
  2x -0:18.9.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 12x -0:18.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
  3x -0:17.3.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:16.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:13.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:13.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:12.6.0 key-binding-resolver:toggle (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:09.9.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:04.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  6x -0:04.3.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ex-mode, v0.4.1
indent-guide-improved, v1.2.0
language-haml, v0.20.0
linter, v0.12.2
linter-haml, v0.4.0
vim-mode, v0.47.0
vim-surround, v0.6.0

# Dev
No dev packages
```

**Comment by kevinsawicki** [comment]
Thanks so much for reporting this.
