### ISSUE TITLE
Error in key press ESC

### ISSUE THREAD

**Issue by thiagoadriano** [atom/keybinding-resolver#31]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Unknown Windows Version
**Thrown From**: [keybinding-resolver](https://github.com/atom/keybinding-resolver) package, v0.33.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar'

```
At fs.js:519

Error: ENOENT: no such file or directory, open 'C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar'
  at Error (native)
  at fs.openSync (fs.js:544:18)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:402:12)
  at compileFileAtPath (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:64:23)
  at Object.defineProperty.value [as .js] (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\src\compile-cache.js:168:18)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.createView (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\keybinding-resolver\lib\main.js:31:34)
  at atom-workspace.atom.commands.add.core:cancel (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\keybinding-resolver\lib\main.js:18:26)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:245:29)
  at C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\thiago.adriano\AppData\Local\atom\app-1.0.11\resources\app.asar\src\window-event-handler.js:184:20)

```

### Commands

```
     -0:35.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:35.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:34.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:33.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:33.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:32.7.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:32.7.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:32.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:32.2.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:31.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:31.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:27.6.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:27.6.0 core:cancel (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by BinaryMuse** [comment]
This is an older issue and doesn't have any reproduction steps to it, so I'm going to close it. Feel free to open it with more details if they're available!
