### ISSUE TITLE
Uncaught TypeError: KeyBindingResolverView is not a constructor

### ISSUE THREAD

**Issue by woolgathering** [atom/keybinding-resolver#69]
Not sure how reproducable it is. Every time I hit Esc or any key combination I receive this error. Started yesterday, not exactly sure why. Literally just reinstalled Atom to make sure I didn't mess up something. Trying to avoid deleting ~/.atom.

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Ubuntu 18.04.1
**Thrown From**: [keybinding-resolver](https://github.com/atom/keybinding-resolver) package 0.38.4

### Stack Trace

Uncaught TypeError: KeyBindingResolverView is not a constructor

```
At /home/roger/.atom/packages/keybinding-resolver/lib/main.js:22

TypeError: KeyBindingResolverView is not a constructor
    at Object.getKeybindingResolverView (/packages/keybinding-resolver/lib/main.js:22:37)
    at /packages/keybinding-resolver/lib/main.js:15:33)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:347327)
    at KeymapManager.t.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1226800)
    at KeymapManager.t.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1222934)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:282763)
```

### Commands

```
     -0:08.4.0 editor:consolidate-selections (input.hidden-input)
     -0:08.4.0 core:cancel (input.hidden-input)
     -0:08.0 editor:consolidate-selections (input.hidden-input)
     -0:08.0 core:cancel (input.hidden-input)
     -0:07.7.0 editor:consolidate-selections (input.hidden-input)
     -0:07.7.0 core:cancel (input.hidden-input)
     -0:07.3.0 editor:consolidate-selections (input.hidden-input)
     -0:07.3.0 core:cancel (input.hidden-input)
     -0:06.3.0 editor:consolidate-selections (input.hidden-input)
     -0:06.3.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
atom-latex 0.8.5 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
atom-python-virtualenv 1.0.2 
atom-updater-linux 1.3.0 
autocomplete-python 1.11.0 
busy-signal 1.4.3 
expand-region 0.4.2 
font-viewer 0.3.1 
git-plus 8.1.0 
highlight-selected 0.14.0 
Hydrogen 2.6.0 
intentions 1.1.5 
language-cmake 1.1.0 
language-faust 0.1.0 
language-latex 1.2.0 
language-matlab 0.2.1 
local-history 4.3.1 
markdown-pdf 2.2.0 
markdown-preview-plus 3.7.1 
multi-cursor 2.1.5 
pdf-view 0.71.0 
platformio-ide-terminal 2.8.4 
processing 0.13.0 
processing-language 0.2.0 
script 3.18.1 
sequential-number 0.5.0 
supercollider 0.9.1 
tabs-to-spaces 1.0.5 
woolgathering-dark-syntax 1.9.1 
woolgathering-light-syntax 1.9.1 
```

**Comment by woolgathering** [comment]
Fixed. Completely deleted and reinstalled Atom and removed keybinding-resolver.
